INSERT INTO adm_tipo_documento (id, codigo, descripcion, formato_usuario,tipo_persona) VALUES (1, 'CI', 'C.I.', '9999','pj');
insert into adm_tipo_documento(id, codigo, descripcion, formato_usuario, tipo_persona) values(2,'RUT','Documento Empresa','0000','pf');
insert into adm_tipo_documento(id, codigo, descripcion, formato_usuario, tipo_persona) values(3,'NDC','Numero documento','0000',null);
INSERT INTO adm_permiso(id,codigo, descripcion)VALUES (1,'1', 'Total');
insert into sga_tipo_relacion(id, tipo_relacion) values(1,'Apoderado');
insert into sga_tipo_relacion(id, tipo_relacion) values(2,'Representante Legal');
insert into sga_tipo_relacion(id, tipo_relacion) values(3,'Apoderado');
insert into sga_tipo_relacion(id, tipo_relacion) values(4,'Representante Legal');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	1	,'AF', 'Afganistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	2	,'AX', 'Islas Gland');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	3	,'AL', 'Albania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	4	,'DE', 'Alemania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	5	,'AD', 'Andorra');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	6	,'AO', 'Angola');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	7	,'AI', 'Anguilla');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	8	,'AQ', 'Antártida');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	9	,'AG', 'Antigua y Barbuda');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	10	,'AN', 'Antillas Holandesas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	11	,'SA', 'Arabia Saudí');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	12	,'DZ', 'Argelia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	13	,'AR', 'Argentina');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	14	,'AM', 'Armenia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	15	,'AW', 'Aruba');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	16	,'AU', 'Australia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	17	,'AT', 'Austria');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	18	,'AZ', 'Azerbaiyán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	19	,'BS', 'Bahamas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	20	,'BH', 'Bahréin');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	21	,'BD', 'Bangladesh');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	22	,'BB', 'Barbados');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	23	,'BY', 'Bielorrusia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	24	,'BE', 'Bélgica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	25	,'BZ', 'Belice');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	26	,'BJ', 'Benin');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	27	,'BM', 'Bermudas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	28	,'BT', 'Bhután');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	29	,'BO', 'Bolivia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	30	,'BA', 'Bosnia y Herzegovina');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	31	,'BW', 'Botsuana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	32	,'BV', 'Isla Bouvet');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	33	,'BR', 'Brasil');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	34	,'BN', 'Brunéi');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	35	,'BG', 'Bulgaria');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	36	,'BF', 'Burkina Faso');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	37	,'BI', 'Burundi');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	38	,'CV', 'Cabo Verde');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	39	,'KY', 'Islas Caimán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	40	,'KH', 'Camboya');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	41	,'CM', 'Camerún');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	42	,'CA', 'Canadá');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	43	,'CF', 'República Centroafricana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	44	,'TD', 'Chad');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	45	,'CZ', 'República Checa');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	46	,'CL', 'Chile');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	47	,'CN', 'China');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	48	,'CY', 'Chipre');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	49	,'CX', 'Isla de Navidad');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	50	,'VA', 'Ciudad del Vaticano');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	51	,'CC', 'Islas Cocos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	52	,'CO', 'Colombia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	53	,'KM', 'Comoras');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	54	,'CD', 'República Democrática del Congo');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	55	,'CG', 'Congo');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	56	,'CK', 'Islas Cook');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	57	,'KP', 'Corea del Norte');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	58	,'KR', 'Corea del Sur');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	59	,'CI', 'Costa de Marfil');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	60	,'CR', 'Costa Rica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	61	,'HR', 'Croacia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	62	,'CU', 'Cuba');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	63	,'DK', 'Dinamarca');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	64	,'DM', 'Dominica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	65	,'DO', 'República Dominicana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	66	,'EC', 'Ecuador');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	67	,'EG', 'Egipto');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	68	,'SV', 'El Salvador');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	69	,'AE', 'Emiratos Árabes Unidos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	70	,'ER', 'Eritrea');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	71	,'SK', 'Eslovaquia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	72	,'SI', 'Eslovenia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	73	,'ES', 'España');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	74	,'UM', 'Islas ultramarinas de Estados Unidos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	75	,'US', 'Estados Unidos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	76	,'EE', 'Estonia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	77	,'ET', 'Etiopía');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	78	,'FO', 'Islas Feroe');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	79	,'PH', 'Filipinas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	80	,'FI', 'Finlandia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	81	,'FJ', 'Fiyi');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	82	,'FR', 'Francia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	83	,'GA', 'Gabón');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	84	,'GM', 'Gambia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	85	,'GE', 'Georgia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	86	,'GS', 'Islas Georgias del Sur y Sandwich del Sur');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	87	,'GH', 'Ghana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	88	,'GI', 'Gibraltar');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	89	,'GD', 'Granada');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	90	,'GR', 'Grecia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	91	,'GL', 'Groenlandia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	92	,'GP', 'Guadalupe');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	93	,'GU', 'Guam');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	94	,'GT', 'Guatemala');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	95	,'GF', 'Guayana Francesa');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	96	,'GN', 'Guinea');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	97	,'GQ', 'Guinea Ecuatorial');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	98	,'GW', 'Guinea-Bissau');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	99	,'GY', 'Guyana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	100	,'HT', 'Haití');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	101	,'HM', 'Islas Heard y McDonald');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	102	,'HN', 'Honduras');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	103	,'HK', 'Hong Kong');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	104	,'HU', 'Hungría');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	105	,'IN', 'India');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	106	,'ID', 'Indonesia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	107	,'IR', 'Irán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	108	,'IQ', 'Iraq');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	109	,'IE', 'Irlanda');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	110	,'IS', 'Islandia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	111	,'IL', 'Israel');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	112	,'IT', 'Italia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	113	,'JM', 'Jamaica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	114	,'JP', 'Japón');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	115	,'JO', 'Jordania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	116	,'KZ', 'Kazajstán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	117	,'KE', 'Kenia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	118	,'KG', 'Kirguistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	119	,'KI', 'Kiribati');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	120	,'KW', 'Kuwait');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	121	,'LA', 'Laos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	122	,'LS', 'Lesotho');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	123	,'LV', 'Letonia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	124	,'LB', 'Líbano');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	125	,'LR', 'Liberia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	126	,'LY', 'Libia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	127	,'LI', 'Liechtenstein');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	128	,'LT', 'Lituania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	129	,'LU', 'Luxemburgo');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	130	,'MO', 'Macao');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	131	,'MK', 'ARY Macedonia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	132	,'MG', 'Madagascar');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	133	,'MY', 'Malasia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	134	,'MW', 'Malawi');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	135	,'MV', 'Maldivas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	136	,'ML', 'Malí');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	137	,'MT', 'Malta');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	138	,'FK', 'Islas Malvinas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	139	,'MP', 'Islas Marianas del Norte');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	140	,'MA', 'Marruecos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	141	,'MH', 'Islas Marshall');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	142	,'MQ', 'Martinica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	143	,'MU', 'Mauricio');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	144	,'MR', 'Mauritania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	145	,'YT', 'Mayotte');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	146	,'MX', 'México');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	147	,'FM', 'Micronesia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	148	,'MD', 'Moldavia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	149	,'MC', 'Mónaco');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	150	,'MN', 'Mongolia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	151	,'MS', 'Montserrat');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	152	,'MZ', 'Mozambique');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	153	,'MM', 'Myanmar');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	154	,'NA', 'Namibia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	155	,'NR', 'Nauru');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	156	,'NP', 'Nepal');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	157	,'NI', 'Nicaragua');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	158	,'NE', 'Níger');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	159	,'NG', 'Nigeria');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	160	,'NU', 'Niue');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	161	,'NF', 'Isla Norfolk');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	162	,'NO', 'Noruega');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	163	,'NC', 'Nueva Caledonia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	164	,'NZ', 'Nueva Zelanda');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	165	,'OM', 'Omán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	166	,'NL', 'Países Bajos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	167	,'PK', 'Pakistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	168	,'PW', 'Palau');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	169	,'PS', 'Palestina');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	170	,'PA', 'Panamá');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	171	,'PG', 'Papúa Nueva Guinea');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	172	,'PY', 'Paraguay');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	173	,'PE', 'Perú');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	174	,'PN', 'Islas Pitcairn');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	175	,'PF', 'Polinesia Francesa');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	176	,'PL', 'Polonia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	177	,'PT', 'Portugal');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	178	,'PR', 'Puerto Rico');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	179	,'QA', 'Qatar');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	180	,'GB', 'Reino Unido');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	181	,'RE', 'Reunión');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	182	,'RW', 'Ruanda');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	183	,'RO', 'Rumania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	184	,'RU', 'Rusia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	185	,'EH', 'Sahara Occidental');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	186	,'SB', 'Islas Salomón');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	187	,'WS', 'Samoa');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	188	,'AS', 'Samoa Americana');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	189	,'KN', 'San Cristóbal y Nevis');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	190	,'SM', 'San Marino');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	191	,'PM', 'San Pedro y Miquelón');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	192	,'VC', 'San Vicente y las Granadinas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	193	,'SH', 'Santa Helena');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	194	,'LC', 'Santa Lucía');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	195	,'ST', 'Santo Tomé y Príncipe');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	196	,'SN', 'Senegal');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	197	,'CS', 'Serbia y Montenegro');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	198	,'SC', 'Seychelles');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	199	,'SL', 'Sierra Leona');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	200	,'SG', 'Singapur');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	201	,'SY', 'Siria');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	202	,'SO', 'Somalia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	203	,'LK', 'Sri Lanka');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	204	,'SZ', 'Suazilandia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	205	,'ZA', 'Sudáfrica');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	206	,'SD', 'Sudán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	207	,'SE', 'Suecia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	208	,'CH', 'Suiza');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	209	,'SR', 'Surinam');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	210	,'SJ', 'Svalbard y Jan Mayen');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	211	,'TH', 'Tailandia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	212	,'TW', 'Taiwán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	213	,'TZ', 'Tanzania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	214	,'TJ', 'Tayikistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	215	,'IO', 'Territorio Británico del Océano Índico');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	216	,'TF', 'Territorios Australes Franceses');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	217	,'TL', 'Timor Oriental');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	218	,'TG', 'Togo');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	219	,'TK', 'Tokelau');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	220	,'TO', 'Tonga');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	221	,'TT', 'Trinidad y Tobago');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	222	,'TN', 'Túnez');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	223	,'TC', 'Islas Turcas y Caicos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	224	,'TM', 'Turkmenistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	225	,'TR', 'Turquía');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	226	,'TV', 'Tuvalu');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	227	,'UA', 'Ucrania');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	228	,'UG', 'Uganda');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	229	,'UY', 'Uruguay');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	230	,'UZ', 'Uzbekistán');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	231	,'VU', 'Vanuatu');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	232	,'VE', 'Venezuela');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	233	,'VN', 'Vietnam');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	234	,'VG', 'Islas Vírgenes Británicas');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	235	,'VI', 'Islas Vírgenes de los Estados Unidos');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	236	,'WF', 'Wallis y Futuna');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	237	,'YE', 'Yemen');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	238	,'DJ', 'Yibuti');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	239	,'ZM', 'Zambia');
INSERT INTO  adm_pais (id, codigo, descripcion) VALUES  (	240	,'ZW', 'Zimbabue');
